
[k8s-master]
ec2-3-238-117-40.compute-1.amazonaws.com
  
[worker]
TODO: add 4 workersk

[cluster:children]
k8-master
worker

[cluster:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_user=ubuntu
